spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentapi
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: debug

BASE_URL: https://localhost:8081
STRIPE_SECRET_KEY: INPUT_YOUR_SECRET_KEY
